config/routes.rb
Rails.application.routes.draw do
  root 'chat_gpt#index'

  post 'send_message', to: 'chat_gpt#send_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_gpt_controller.rb
class ChatGptController < ApplicationController
  def index
  end

  def send_message
    api = ChatGptApi.new()
    @gptresponse = api.ask(params[:message])
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_gpt_helper.rb
module ChatGptHelper
end

app/views/chat_gpt/_form.html.erb
<%= form_tag(send_message_path, method: "post", data: { turbo: "false" }) do %>
  <div class="field">
    <label for="message">Ask ChatGPT:</label>
    <textarea name="message" id="message" rows="5" cols="30"></textarea>
  </div>
  
  <div class="field">
    <button class="btn-primary" type="submit">Send Message</button>
  </div>
<% end %>

app/views/chat_gpt/index.html.erb
<div class="container mx-auto">
  <div class="flex justify-center py-10">

    <%= render "form" %>

  </div>
  <div class="flex justify-center py-10">
    <% if @gptresponse %>
      <div class="prose">
        <strong>Response:</strong>
        <p><%= @gptresponse %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LlmRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>